backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# This line should *not* be indented
# These lines should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
show_preview_links: false

collections:
  - name: "barbers"
    label: "Barbers"
    files: 
      - label: "Barbers List"
        name: "Barbers-list"
        file: site/settings/Barbers.json
        fields:
          - label: "Barber"
            name: "barber"
            widget: "list"
            allow_add: true
            fields:
              - {label: "Barber Name", name: "name", widget: "string"}
              - {label: "Phone Number {Enter without spaces. Ex 1234567890}", required: false, name: "phone", widget: "string"}
              - {label: "Barber's Photo", name: "photo", widget: "image"}
              - {label: "Barber's Description", name: "description", widget: "text"}
  - name: "front-page"
    label: "Front Page Picture"
    files:
      - label: "Picture"
        name: "front-page-picture"
        file: site/settings/FrontPage.json
        fields:
          - { label: "Landscape Photo", name: "landscape", widget: "image" }
          - { label: "Portrait Photo", name: "portrait", widget: "image"}
  - name: "header"
    label: "Header Formatting"
    files:
      - label: "Header Links"
        name: "links"
        file: site/settings/HeaderLinks.json
        fields:
          - label: "link-set"
            name: "LinkSet"
            widget: "list"
            allow_add: true
            fields:
              - { label: "HTTPS Link (The https://www. Link)", name: "LinkURL", widget: "string"}
              - { label: "Link Label (What Users Will See)", name: "LinkName", widget: "string"}

