backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# This line should *not* be indented
# These lines should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
show_preview_links: false

collections:
  - name: "barbers"
    label: "Barbers"
    files: 
      - label: "Barbers List"
        name: "Barbers-list"
        file: site/settings/barbers.json
        fields:
          - label: "Barber"
            name: "barber"
            widget: "list"
            allow_add: true
            fields:
              - {label: "Barber Name", name: "name", widget: "Text"}
              - {label: "Phone Number {Format as: (111) 222-333}", required: false, name: "phone", widget: "Text"}
              - {label: "Barber's Photo", name: "photo", widget: "image"}
              - {label: "Barber's Description", name: "description", widget: "text"}
  - name: "front-page"
    label: "Front Page Picture"
    files:
      - label: "Picture"
        name: "front-page-picture"
        file: site/settings/Front-Page.json
        fields:
          - { label: "Picture", name: "Store-Picture", widget: "image" }
          - { label: "Updated", name: "update-date", widget: "datetime"}