backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# This line should *not* be indented
# These lines should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
show_preview_links: false

collections:
  - name: "barbers"
    label: "Barbers"
    files: 
      - label: "Barbers List"
        name: "Barbers-list"
        file: site/settings/barbers.json
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Photo", name: "picture", widget: "image"}
          - { label: "Phone", name: "phone",  widget: "string"}
          - { label: "Description", name: "description", widget: "text"}
  - name: "front-page"
    label: "Front Page Picture"
    files:
      - label: "Picture"
        name: "front-page-picture"
        file: site/settings/Front-Page.json
        fields:
          - { label: "Picture", name: "Store-Picture", widget: "image" }
          - { label: "Updated", name: "update-date", widget: "datetime"}